<?php
require_once __DIR__ . "/env.php";
require_once __DIR__ . "/config.php";
require_once __DIR__ . "/vendor/autoload.php";
session_start();

use App\Models\ProductModel;
use App\Router;
use App\Controllers\HomeController;
use App\Controllers\AccountController;
use App\Controllers\CategoryController;
use App\Controllers\BlogController;
use App\Controllers\ProductController;
use App\Controllers\AuthController;

$router = new Router();
Router::get('/index.php', [HomeController::class, 'index']);
Router::get('/', [HomeController::class, 'index']);
Router::get('/home', [HomeController::class, 'index']);
Router::get('/productsByCategory', [HomeController::class, 'productsByCategory']);
Router::get('/detail', [HomeController::class, 'detail']);
Router::get('/blog', [HomeController::class, 'blog']);
Router::get('/admin/account', [AccountController::class, 'lists']);
Router::get('/account/create', [AccountController::class, 'add']);
Router::post('/account/create', [AccountController::class, 'store']);
Router::get('/account/edit', [AccountController::class, 'inforAccount']);
Router::post('/account/edit', [AccountController::class, 'editAccount']);
Router::get('/account/detail', [AccountController::class, 'detailAccount']);
Router::get('/admin/account/delete', [AccountController::class, 'deleteAccount']);
Router::get('/admin/category', [CategoryController::class, 'lists']);
Router::get('/category/create', [CategoryController::class, 'add']);
Router::post('/category/create', [CategoryController::class, 'store']);
Router::get('/category/edit', [CategoryController::class, 'getInfoCategory']);
Router::post('/category/edit', [CategoryController::class, 'updateCategory']);
Router::get('/admin/category/delete', [CategoryController::class, 'deleteCategory']);
Router::get('/admin/blog', [BlogController::class, 'list']);
Router::get('/blog/create', [BlogController::class, 'add']);
Router::post('/blog/create', [BlogController::class, 'store']);
Router::get('/blog/edit', [BlogController::class, 'getInfoBlog']);
Router::post('/blog/edit', [BlogController::class, 'updateBlog']);
Router::get('/blog/delete', [BlogController::class, 'deleteBlog']);
Router::get('/admin/product', [ProductController::class, 'list']);
Router::get('/product/create', [ProductController::class, 'add']);
Router::post('/product/create', [ProductController::class, 'store']);
Router::get('/product/edit', [ProductController::class, 'getProduct']);
Router::post('/product/edit', [ProductController::class, 'editProduct']);
Router::get('/product/delete', [ProductController::class, 'deleteProduct']);
Router::get('/login', [AuthController::class, 'getLogin']);
Router::post('/login', [AuthController::class, 'login']);
Router::get('/register', [AuthController::class, 'getRegister']);
Router::post('/register', [AuthController::class, 'register']);
Router::get('/forgot-password', [AuthController::class, 'getForgotPassword']);
Router::post('/forgot-password', [AuthController::class, 'forgotPassword']);

$router->resolve();
session_destroy();
